// Ability registry — descriptions used by UI; mechanics in game.js
const ABILITIES = {
  Adaptability:   { desc: 'Same-type attacks hit 1.5× harder.' },
  Blaze:          { desc: 'Fire moves deal 1.5× when HP drops below 33%.' },
  'Compound Eyes':{ desc: 'Boosts all move accuracy by 1.3×.' },
  'Flash Fire':   { desc: 'Absorbs Fire moves; own Fire attacks gain 50% power.' },
  'Flame Body':   { desc: '30% chance to burn attackers that make contact.' },
  Guts:           { desc: 'Attack is 1.5× when afflicted with a status condition.' },
  Hustle:         { desc: 'Physical Attack 1.5×, but physical accuracy is ×0.8.' },
  Intimidate:     { desc: "Lowers the foe's Attack one stage on switch-in." },
  Levitate:       { desc: 'Immune to Ground-type moves.' },
  Moxie:          { desc: 'Attack rises one stage after knocking out a foe.' },
  Multiscale:     { desc: 'Halves damage taken when at full HP.' },
  'Natural Cure': { desc: 'Heals all status conditions when switching out.' },
  Overgrow:       { desc: 'Grass moves deal 1.5× when HP drops below 33%.' },
  'Poison Heal':  { desc: 'Restores HP each turn while poisoned instead of losing it.' },
  'Poison Point': { desc: '30% chance to poison attackers that make contact.' },
  Regenerator:    { desc: 'Restores 33% HP when switching out.' },
  'Rough Skin':   { desc: 'Damages contact attackers for 1/8 of their max HP.' },
  'Serene Grace': { desc: 'Doubles the chance of move secondary effects.' },
  'Shed Skin':    { desc: '33% chance to cure status conditions at end of each turn.' },
  'Shell Armor':  { desc: 'Cannot be struck by a critical hit.' },
  'Speed Boost':  { desc: 'Speed rises one stage at the end of each turn.' },
  Static:         { desc: '30% chance to paralyze attackers that make contact.' },
  Sturdy:         { desc: 'Survives any one-hit KO with 1 HP remaining (from full HP).' },
  Swarm:          { desc: 'Bug moves deal 1.5× when HP drops below 33%.' },
  'Thick Fat':    { desc: 'Halves damage from Fire and Ice moves.' },
  Torrent:        { desc: 'Water moves deal 1.5× when HP drops below 33%.' },
  'Water Absorb': { desc: 'Restores 25% HP when hit by a Water-type move.' },
};
